name: Test
on: [push, pull_request]
jobs:
  lint:
    strategy:
      matrix:
        go-versions: [1.14]
        platform: [ubuntu-latest]
        environment-variables: [build/config/plain.sh, build/config/libpfm4.sh]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-versions }}
#    This is not the most elegant way of installing golangci-lint but I have filed a PR
#    and I will fix it as soon as it's merged: https://github.com/golangci/golangci-lint/pull/1036
#    cAdvisor has existed for a while without golint and we need to figure out how to
#    fix issues affecting exported identifiers that are part of public API. Let's avoid breaking Kubernetes.
    - name: Install golangci-lint
      run: |
        go get -d github.com/golangci/golangci-lint/cmd/golangci-lint &&
        cd $(go env GOPATH)/src/github.com/golangci/golangci-lint/ &&
        git remote add iwankgb https://github.com/iwankgb/golangci-lint.git &&
        git fetch iwankgb &&
        git reset --hard iwankgb/exclude-case-sensitive &&
        go install -i github.com/golangci/golangci-lint/cmd/golangci-lint
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      run: source ${{ matrix.environment-variables }} && make lint
  test:
    strategy:
      matrix:
        go-versions: [1.13, 1.14]
        platform: [ubuntu-latest]
        environment-variables: [build/config/plain.sh, build/config/libpfm4.sh]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-versions }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run presubmit checks
      run: GOFLAGS="$GO_FLAGS" make presubmit
    - name: Run tests
      env:
        GOLANG_VERSION: ${{ matrix.go-versions }}
      run: source ${{ matrix.environment-variables }} && make docker-test
  test-integration:
    strategy:
      matrix:
        go-versions: [1.13, 1.14]
        platform: [ubuntu-latest]
        environment-variables: [build/config/plain.sh, build/config/libpfm4.sh]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/google/cadvisor
    - name: Run integration tests
      env:
        GOLANG_VERSION: ${{ matrix.go-versions }}
      run: |
        cd $GITHUB_WORKSPACE/go/src/github.com/google/cadvisor && source ${{ matrix.environment-variables }} && make docker-test-integration
    - name: Upload cAdvisor log file
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cadvisor.log
        path: ${{ github.workspace }}/go/src/github.com/google/cadvisor/cadvisor.log
  test-integration-s390x:
    runs-on: ubuntu-18.04
    name: Build on s390x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/google/cadvisor
      - uses: dims/run-on-arch-action@master
        with:
          architecture: s390x
          distribution: ubuntu18.04
          run: |
            set -euo pipefail
            apt-get update
            apt-get install -y --no-install-recommends \
            apt-transport-https \
            ca-certificates \
            socat \
            curl \
            gnupg2 \
            software-properties-common \
            lsb-release \
            build-essential \
            git

            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            add-apt-repository \
               "deb [arch=s390x] https://download.docker.com/linux/ubuntu \
               $(lsb_release -cs) stable"

            apt-get update
            apt-cache madison docker-ce
            apt-get install -y --no-install-recommends docker-ce=18.06.*

            curl https://dl.google.com/go/go1.13.8.linux-s390x.tar.gz -o /tmp/go.tar.gz
            tar -C /usr/local -xzf /tmp/go.tar.gz
            export PATH="$PATH":/usr/local/go/bin

            set -x
            cd $GITHUB_WORKSPACE/go/src/github.com/google/cadvisor && source build/config/plain.sh && make test-integration
